CREATE SCHEMA `challenge` DEFAULT CHARACTER SET utf8;
use challenge;

CREATE TABLE equipment (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    equipmentId TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    value REAL NOT NULL
);

CREATE TABLE user (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);